"""Export OpenAPI JSON and a TypeScript contract file."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def openapi_to_ts(schema: dict) -> str:
    lines = ["// Generated by scripts/export_contracts.py. Do not edit by hand.", ""]
    schemas = schema.get("components", {}).get("schemas", {})
    for name, spec in schemas.items():
        lines.append(f"export interface {name} {{")
        properties = spec.get("properties") or {}
        required = set(spec.get("required") or [])
        if not properties:
            lines.append("  [key: string]: unknown;")
        for field, field_spec in properties.items():
            optional = "" if field in required else "?"
            ts_type = _ts_type(field_spec)
            lines.append(f"  {field}{optional}: {ts_type};")
        lines.append("}")
        lines.append("")
    paths = schema.get("paths") or {}
    lines.append("export type ApiPaths =")
    for path in paths:
        lines.append(f"  | {json.dumps(path)}")
    if not paths:
        lines.append("  | never")
    lines.append(";")
    lines.append("")
    return "\n".join(lines)


def _ts_type(spec: dict) -> str:
    if "$ref" in spec:
        return str(spec["$ref"]).rsplit("/", 1)[-1]
    mapping = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "object": "Record<string, unknown>",
    }
    if spec.get("type") == "array":
        return f"Array<{_ts_type(spec.get('items') or {})}>"
    if "anyOf" in spec or "oneOf" in spec:
        variants = spec.get("anyOf") or spec.get("oneOf") or []
        return " | ".join(_ts_type(item) for item in variants) or "unknown"
    return mapping.get(str(spec.get("type")), "unknown")


def main() -> None:
    from color_rush.api.app import create_app

    app = create_app()
    schema = app.openapi()
    contracts = ROOT / "contracts"
    contracts.mkdir(exist_ok=True)
    openapi_path = contracts / "openapi.json"
    openapi_path.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")
    ts_dir = contracts / "ts"
    ts_dir.mkdir(exist_ok=True)
    (ts_dir / "api.d.ts").write_text(openapi_to_ts(schema), encoding="utf-8")
    print(f"wrote {openapi_path} and {ts_dir / 'api.d.ts'}")


if __name__ == "__main__":
    main()
