// Generated by scripts/export_contracts.py. Do not edit by hand.

export interface AdminUserCreateRequest {
  username: string;
  password: string;
  role: string;
}

export interface AutoModeRequest {
  session_id: string;
  mode: SessionMode;
  expected_revision?: number | unknown;
}

export interface BonusType {
  [key: string]: unknown;
}

export interface CancelRequest {
  session_id: string;
  reason: string;
  expected_revision?: number | unknown;
}

export interface Color {
  [key: string]: unknown;
}

export interface GameCreateRequest {
  name?: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface ModerationRequest {
  scope_key: string;
  blocked: boolean;
  reason?: string | unknown;
}

export interface NextBonusRequest {
  session_id: string;
  bonus: BonusType;
  gold_reward?: number;
  expected_revision?: number | unknown;
}

export interface OverlayTicketCreateRequest {
  game_id: string;
  session_id?: string | unknown;
  label?: string;
}

export interface OverlayTicketCreated {
  ticket_id: string;
  secret: string;
  obs_url: string;
}

export interface RefreshRequest {
  refresh_token: string;
}

export interface RoundStartRequest {
  session_id: string;
  expected_revision?: number | unknown;
}

export interface SeasonCreateRequest {
  game_id: string;
  name: string;
  starts_at: string;
  ends_at: string;
}

export interface SessionActionRequest {
  session_id: string;
  expected_revision?: number | unknown;
}

export interface SessionCreateRequest {
  game_id: string;
  mode?: SessionMode;
  source_mode?: string;
  expected_revision?: number | unknown;
}

export interface SessionMode {
  [key: string]: unknown;
}

export interface SettingsPutRequest {
  game_id: string;
  session_id?: string | unknown;
  configuration: Record<string, unknown>;
  expected_revision?: number | unknown;
}

export interface SimCommand {
  session_id: string;
  broadcast_id?: string;
  provider_channel_id: string;
  display_name: string;
  text: string;
  published_at: string;
  message_id: string;
}

export interface SimSpin {
  session_id: string;
  fence_token: number;
  forced?: Color | unknown;
}

export interface SimStartRound {
  session_id: string;
  fence_token: number;
}

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
  role: string;
  user_id: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface YoutubeConnectRequest {
  session_id: string;
  video_ref: string;
  expected_revision?: number | unknown;
}

export interface YoutubeOAuthRevokeRequest {
  game_id: string;
}

export interface YoutubeOAuthStartRequest {
  game_id: string;
}

export type ApiPaths =
  | "/health/live"
  | "/health/ready"
  | "/metrics"
  | "/api/v1/auth/login"
  | "/api/v1/auth/refresh"
  | "/api/v1/auth/logout"
  | "/api/v1/game/snapshot"
  | "/api/v1/rounds/{round_id}"
  | "/api/v1/leaderboards"
  | "/api/v1/periods/{period_id}/champions"
  | "/api/v1/periods/{period_id}/archives"
  | "/api/v1/players"
  | "/api/v1/players/{player_id}/ranks"
  | "/api/v1/periods"
  | "/api/v1/admin/health"
  | "/api/v1/admin/audit"
  | "/api/v1/admin/games"
  | "/api/v1/admin/sessions"
  | "/api/v1/admin/sessions/{session_id}"
  | "/api/v1/admin/rounds"
  | "/api/v1/admin/rounds/start"
  | "/api/v1/admin/rounds/{round_id}/close"
  | "/api/v1/admin/rounds/{round_id}/spin"
  | "/api/v1/admin/rounds/{round_id}/cancel"
  | "/api/v1/admin/session/pause"
  | "/api/v1/admin/session/resume"
  | "/api/v1/admin/session/auto-mode"
  | "/api/v1/admin/next-round-bonus"
  | "/api/v1/admin/settings"
  | "/api/v1/admin/seasons"
  | "/api/v1/admin/players/{player_id}/moderation"
  | "/api/v1/admin/players/{player_id}/delete-data"
  | "/api/v1/admin/youtube/connect"
  | "/api/v1/admin/youtube/disconnect"
  | "/api/v1/admin/youtube/oauth/start"
  | "/api/v1/admin/youtube/oauth/callback"
  | "/api/v1/admin/youtube/oauth/status"
  | "/api/v1/admin/youtube/oauth/revoke"
  | "/api/v1/admin/users"
  | "/api/v1/admin/overlay-tickets"
  | "/api/v1/admin/overlay-tickets/{ticket_id}/revoke"
  | "/api/v1/admin/periods/finalize"
  | "/api/v1/admin/source"
  | "/simulation/commands"
  | "/simulation/rounds/start"
  | "/simulation/rounds/close"
  | "/simulation/rounds/drain"
  | "/simulation/rounds/spin"
  | "/simulation/rounds/settle"
  | "/overlay"
;
